/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'adixit' at '11/25/20 9:37 PM' with Gradle 3.0
 *
 * @author adixit, @date 11/25/20 9:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
